// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'google_api_key',
    appId: 'google_api_id',
    messagingSenderId: 'sender_id',
    projectId: 'proj_id',
    authDomain: 'text-quiz.firebaseapp.com',
    storageBucket: 'text-quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'google_api_key',
    appId: 'google_api_id',
    messagingSenderId: 'sender_id',
    projectId: 'proj_id',
    storageBucket: 'text-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'google_api_key',
    appId: 'google_api_id',
    messagingSenderId: 'sender_id',
    projectId: 'proj_id',
    storageBucket: 'text-quiz.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'google_api_key',
    appId: 'google_api_id',
    messagingSenderId: 'sender_id',
    projectId: 'proj_id',
    storageBucket: 'text-quiz.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'google_api_key',
    appId: 'google_api_id',
    messagingSenderId: 'sender_id',
    projectId: 'proj_id',
    authDomain: 'text-quiz.firebaseapp.com',
    storageBucket: 'text-quiz.firebasestorage.app',
  );
}